hotjs.i18n.put('en', {
	'fastsignup': 'Fast Sign Up',
	'signup': 'Sign Up',
	'login': 'Login',
	'logout': 'Logout',
	'available games': 'Available games',
	'login success': 'Login success',
	'not in room': 'Not in room',
	'entergame': 'Enter',
	'enter': 'Enter',
	'room number': 'Room number',
	'gamers in room': 'Gamers in room',
	'chat': 'Chat',
	'jinhua1': 'Classic Jinhua',
	'jinhua2': 'PK Jinhua',
	'holdem1': 'Holdem (Limit)',
	'holdem2': 'Holdem (Pot-Limit)',
	'holdem3': 'Holdem (No-Limit)',
	'exit': 'Exit',
	'say': 'Say',
	'unseat': 'Stand Up',
	'empty': 'empty',
	'at seat': 'at seat',
	'to bet': 'to bet',
	'delay': 'delay',
	'seconds': 'seconds',
	'pot': 'Pot',
	'shared cards': 'Shared cards',
	'private cards': 'Private cards',
	'bet': 'Bet',
	'ready': 'Ready',
	'seecard': 'See Card',
	'showcard': 'Show Card',
	'call': 'Call',
	'raise': 'Raise',
	'fold': 'Fold/Give Up',
	'pk': 'PK',
	'result': 'Result',
	'win': 'Win',
	'fail': 'Fail',
	'count down:': 'Count down: ',
	'now:': 'Now: ',
	'dealing cards': 'Dealing cards ...',
	'game start': 'Game start',
	'take seat': 'Sit',
	'unseat from': 'unseat from',
	'say:': 'say: ',
	'shout:': 'shout: ',
	'game over!': 'Game over!',
	'account created:': 'Account created: ',
	'uid': 'UID',
	'passwd': 'Password',
	'name': 'Nick',
	'email': 'Email',
	'phone': 'Phone',
	'uuid': 'UUID',
});
