hotjs.i18n.put('en', {
	'fastsignup': 'Fast SignUp',
	'signup': 'Sign Up',
	'login': 'Login',
	'logout': 'Logout',
	'entergame': 'Enter',
	'chat': 'Chat',
	'jinhua1': 'Classic Jinhua',
	'jinhua2': 'PK Jinhua',
	'holdem1': 'Holdem (Limit)',
	'holdem2': 'Holdem (Pot-Limit)',
	'holdem3': 'Holdem (No-Limit)',
	'exit': 'Exit',
	'say': 'Say',
	'takeseat': 'Sit',
	'unseat': 'Stand Up',
	'ready': 'Ready',
	'seecard': 'See Card',
	'showcard': 'Show Card',
	'call': 'Call',
	'raise': 'Raise',
	'fold': 'Fold/GiveUp',
	'pk': 'PK',
	'count down:': 'Count down:',
	'now:': 'Now:',
	'dealing cards': 'Dealing cards ...',
});
