hotjs.i18n.put('zh', {
	'fastsignup': '快速注册',
	'signup': '注册',
	'login': '登录',
	'logout': '登出',
	'entergame': '进入',
	'enter': '进入',
	'chat': '聊天',
	'jinhua1': '经典扎金花',
	'jinhua2': '大牌扎金花',
	'holdem1': '德州扑克（限注）',
	'holdem2': '德州扑克（彩池限注）',
	'holdem3': '德州扑克（无限下注）',
	'exit': '离开房间',
	'say': '说',
	'takeseat': '入座',
	'unseat': '离座',
	'ready': '准备',
	'seecard': '看牌',
	'showcard': '亮牌',
	'call': '跟注',
	'raise': '加注',
	'fold': '盖牌/弃牌',
	'pk': '比牌',
	'count down:': '倒计时：',
	'now:': '现在：',
	'dealing cards': '正在发牌',
	'game start': '牌局开始',
	'take seat': '入座',
	'unseat from': '离座',
	'say:': '说：',
	'shout:': '大吼：',
	'game over!': '牌局结束！',
	'account created:': '账号已创建',
	'uid': '登录名',
	'passwd': '密码',
	'name': '昵称',
	'email': 'Email',
	'phone': '电话号码',
	'uuid': 'UUID',
});
